### ISSUE TITLE
FindRandomPointAroundCircle IndexOutOfRangeException

### ISSUE THREAD

**Issue by AqlaSolutions** [Robmaister/SharpNav#61]
Sometimes it throws
```
FindRandomPointAroundCircle problem: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at SharpNav.Pathfinding.PathfindingCommon.RandomPointInConvexPoly(Vector3[] pts, Int32 npts, Single[] areas, Single s, Single t, Vector3& pt) in D:\Dropbox\DotNet Resources\SharpNav\Source\SharpNav\Pathfinding\PathfindingCommon.cs:line 45
at SharpNav.NavMeshQuery.FindRandomPointOnPoly(MeshTile tile, Poly poly, PolyId polyRef, Vector3& randomPt) in D:\Dropbox\DotNet Resources\SharpNav\Source\SharpNav\NavMeshQuery.cs:line 121
at SharpNav.NavMeshQuery.FindRandomPointAroundCircle(NavPoint center, Single radius, NavPoint& randomPoint) in D:\Dropbox\DotNet Resources\SharpNav\Source\SharpNav\NavMeshQuery.cs:line 410
```

I don't have a specific point logged, only range (99999) and it's very rare but still could you check the code?

**Comment by Robmaister** [comment]
The logic for this exception is fairly straightforward, how it would reach that state worries me a bit.

Regardless, I ensured the exception can never be triggered and cleaned up the APIs for RandomPointInConvexPoly and FindRandomPointOnPoly. The fixes will be included in the next release.

**Comment by AqlaSolutions** [comment]
Looks like it's fixed now.
